name: download

on:
  push:
  workflow_dispatch:

jobs:
  strategy:
    fail-fast: false
    matrix:
      runs: windows-latest
      version:
      - "10"
      - "11"
      lang:
      - "Russian"
      - "English"
      
  download:
    name: download
    uses: ${{matrix.runs}}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Download windows 11
        run: .\Fido.ps1 -Win ${{matrix.version}} -Arch x64 -Lang ${{matrix.lang}} -Ed Pro && ls
          

      - name: upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: windows_iso
          path: .\*.iso
        

        
      
