name: download

on:
  push:
  workflow_dispatch:

jobs:
  download:
    strategy:
      fail-fast: false
      matrix:
        version: ["10", "11"]
        lang: ["Russian", "English"]

    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Windows ISO
        shell: pwsh
        run: |
          .\Fido.ps1 -Win "${{ matrix.version }}" -Arch x64 -Lang "${{ matrix.lang }}" -Ed Pro
          Get-ChildItem -Path . -Filter *.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: windows_iso_${{ matrix.version }}_${{ matrix.lang }}
          path: .\*.iso
