name: download

on:
  push:
  workflow_dispatch:

jobs:
  download:
    name: download
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Download
        run: .\Fido.ps1 -Win 10 -Arch x64 -Lang Russian -GetUrl

      - name: upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: windows_iso
          path: .\*.iso
        

        
      
